### ISSUE TITLE
Cannot read property 'getState' of undefined

### ISSUE THREAD

**Issue by mosesmc52** [jacobrosenthal/react-native-ble#50]
I'm trying to load **react-native-ble** within android using this require function. 

var noble = require('noble');

I'm experiencing this error. Would you know what would be causing this error

Thanks,

Moses

![screen shot 2017-05-08 at 4 10 36 pm](https://cloud.githubusercontent.com/assets/5233925/25825533/e7084f14-3408-11e7-9a8e-bb513c5258fa.png)

**Comment by nielsswinkels** [comment]
How did you solve it?

**Comment by keeslinp** [comment]
@nielsswinkels This is what happens when the native module isn't set up properly. If the problem is on android then go into MainApplication.java and add the necessary RNBLE calls. (You can check the example for how they did it). If it's iOS then you go to build properties for the project and add the libRNBLE.a file.

This is assuming you already ran `react-native link`. Otherwise start with that :)
